find_path(ZLTOOLKIT_INCLUDE_DIR
  NAMES ZLToolKit/Network/Socket.h)

find_library(ZLTOOLKIT_LIBRARY
  NAMES ZLToolKit)

set(ZLTOOLKIT_LIBRARIES ${ZLTOOLKIT_LIBRARY})
set(ZLTOOLKIT_INCLUDE_DIRS ${ZLTOOLKIT_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(ZLTOOLKIT DEFAULT_MSG ZLTOOLKIT_LIBRARY ZLTOOLKIT_INCLUDE_DIR)
