include(FindPackageHandleStandardArgs)

set(_LSQUIC_ROOT_HINTS)
if(DEFINED LSQUIC_ROOT_DIR AND LSQUIC_ROOT_DIR)
  list(APPEND _LSQUIC_ROOT_HINTS ${LSQUIC_ROOT_DIR})
endif()
if(DEFINED ENV{LSQUIC_ROOT_DIR} AND NOT "$ENV{LSQUIC_ROOT_DIR}" STREQUAL "")
  list(APPEND _LSQUIC_ROOT_HINTS $ENV{LSQUIC_ROOT_DIR})
endif()

if(DEFINED LSQUIC_INCLUDE_DIR AND EXISTS "${LSQUIC_INCLUDE_DIR}/lsquic.h")
  set(_LSQUIC_INCLUDE_DIR "${LSQUIC_INCLUDE_DIR}")
else()
  find_path(_LSQUIC_INCLUDE_DIR
    NAMES lsquic.h
    HINTS ${_LSQUIC_ROOT_HINTS}
    PATH_SUFFIXES include src/include)
endif()

if(DEFINED LSQUIC_LIBRARY AND EXISTS "${LSQUIC_LIBRARY}")
  set(_LSQUIC_LIBRARY "${LSQUIC_LIBRARY}")
else()
  set(_LSQUIC_SAVED_SUFFIXES ${CMAKE_FIND_LIBRARY_SUFFIXES})
  if(DEFINED LSQUIC_PREFER_SHARED AND LSQUIC_PREFER_SHARED)
    if(APPLE)
      set(CMAKE_FIND_LIBRARY_SUFFIXES .dylib .so .a)
    elseif(UNIX AND NOT WIN32)
      set(CMAKE_FIND_LIBRARY_SUFFIXES .so .a)
    endif()
  else()
    if(APPLE)
      set(CMAKE_FIND_LIBRARY_SUFFIXES .a .dylib .so)
    elseif(UNIX AND NOT WIN32)
      set(CMAKE_FIND_LIBRARY_SUFFIXES .a .so)
    endif()
  endif()

  find_library(_LSQUIC_LIBRARY
    NAMES lsquic
    HINTS ${_LSQUIC_ROOT_HINTS}
    PATH_SUFFIXES lib lib64 src/liblsquic)
  set(CMAKE_FIND_LIBRARY_SUFFIXES ${_LSQUIC_SAVED_SUFFIXES})
endif()

set(LSQUIC_INCLUDE_DIR ${_LSQUIC_INCLUDE_DIR})
set(LSQUIC_LIBRARY ${_LSQUIC_LIBRARY})
set(LSQUIC_INCLUDE_DIRS ${LSQUIC_INCLUDE_DIR})
set(LSQUIC_LIBRARIES ${LSQUIC_LIBRARY})

set(_LSQUIC_INTERFACE_LINKS)
if(DEFINED LSQUIC_SSL_LIBRARY AND EXISTS "${LSQUIC_SSL_LIBRARY}")
  list(APPEND _LSQUIC_INTERFACE_LINKS ${LSQUIC_SSL_LIBRARY})
endif()
if(DEFINED LSQUIC_CRYPTO_LIBRARY AND EXISTS "${LSQUIC_CRYPTO_LIBRARY}")
  list(APPEND _LSQUIC_INTERFACE_LINKS ${LSQUIC_CRYPTO_LIBRARY})
endif()

if(LSQUIC_LIBRARY)
  get_filename_component(_LSQUIC_LIBRARY_EXT "${LSQUIC_LIBRARY}" EXT)
  if(_LSQUIC_LIBRARY_EXT STREQUAL ".a")
    find_package(Threads QUIET)
    if(Threads_FOUND)
      list(APPEND _LSQUIC_INTERFACE_LINKS Threads::Threads)
    endif()
    if(UNIX AND NOT APPLE)
      list(APPEND _LSQUIC_INTERFACE_LINKS m z)
      find_library(_LSQUIC_RT_LIBRARY rt)
      if(_LSQUIC_RT_LIBRARY)
        list(APPEND _LSQUIC_INTERFACE_LINKS ${_LSQUIC_RT_LIBRARY})
      endif()
    elseif(APPLE)
      list(APPEND _LSQUIC_INTERFACE_LINKS m z)
    endif()
  endif()
endif()

find_package_handle_standard_args(LSQUIC
  REQUIRED_VARS LSQUIC_INCLUDE_DIR LSQUIC_LIBRARY)

if(LSQUIC_FOUND AND NOT TARGET LSQUIC::LSQUIC)
  add_library(LSQUIC::LSQUIC UNKNOWN IMPORTED)
  set_target_properties(LSQUIC::LSQUIC PROPERTIES
    IMPORTED_LOCATION "${LSQUIC_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${LSQUIC_INCLUDE_DIR}")
  if(_LSQUIC_INTERFACE_LINKS)
    set_target_properties(LSQUIC::LSQUIC PROPERTIES
      INTERFACE_LINK_LIBRARIES "${_LSQUIC_INTERFACE_LINKS}")
  endif()
endif()

mark_as_advanced(LSQUIC_INCLUDE_DIR LSQUIC_LIBRARY)
